### ISSUE TITLE
Cannot find name 'global' in angular6

### ISSUE THREAD

**Issue by balajun01** [agoncal/swagger-ui-angular6#1]
After setup is done try to run the code ng serve getting the below mentioned error 

ERROR in src/polyfills.ts(82,1): error TS2304: Cannot find name 'global'.
src/polyfills.ts(82,17): error TS2304: Cannot find name 'global'.
src/polyfills.ts(82,34): error TS2304: Cannot find name 'require'.

**Comment by hnitzsche** [comment]
place `(window as any).global = window;` into your _polyfills.ts_
